spring:
  application:
    name: usuario
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jmx:
    enabled: false
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://192.168.99.100:15432/usuario
server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true