spring:
  application:
    name: usuario
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
  jmx:
    enabled: false
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/curso
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true