version: '3'

services:
  svc-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "15432:5432"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - postgres-compose-network

  svc-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - svc-postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge